name: ChatManager
main: EvCode.ChatManager.ChatManager
Author: EvModder/Evil_Witchdoctor/Anuvin
version: 1.5.4
softdepend: [Vault]
    
commands:
   evcm:
      description: Commands for EvChatManager.
      usage: Do /evcm help for ChatManager commands
      aliases: [chat,chatm,chatmanager,chat-manager,cm,evchatmanager]
      permission: evp.evcm
      permission-message: You do not have permission for this command.
     
permissions:
   evp.evcm:
        description: Allows access to the /chat command
        default: op
        
   evp.evcm.reload:
        description: Reload all configuration settings.
        default: op
        
   evp.evcm.togglespam:
        description: Toggle spam-blocking on/off.
        default: op
        
   evp.evcm.togglefilth:
        description: Toggle chat-filter on/off.
        default: op
        
   evp.evcm.togglecolor:
        description: Toggle chat color usage ability on/off.
        default: false
        
   evp.evcm.toggleformat:
        description: Toggle chat format usage ability on/off.
        default: false
        
   evp.evcm.chatcolor:
        description: Allows players to use colors in chat.
        default: op
        
   evp.evcm.chatformat:
        description: Allows players to use formats in chat.
        default: op
        
   evp.evcm.signcolor:
        description: Allows players to use colors on signs.
        default: op
        
   evp.evcm.signformat:
        description: Allows players to use formats on signs.
        default: op
        
   evp.evcm.spamfilter.exempt:
        description: Chats from this player will not be monitored by the spam-filter
        default: op
        
   evp.evcm.chatfilter.exempt:
        description: Chats from this player will not be monitored by the chat-filter
        default: false